version: '3.8'

services:
  web:
    build: .
    command: python review_parser/manage.py runserver 0.0.0.0:8000
    working_dir: /code/review_parser
    volumes:
      - .:/code/review_parser
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1